modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]] 
modId="tinycoal"
version="${file.jarVersion}" 
displayName="Tiny Coal"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Allows you to convert coal or charcoal to Tiny Coal/Charcoal.
'''
